 # yaml-language-server: $schema=./schema.v2.json

# Configurazione generale
language: "it-IT"
auto_resolve_threads: true
tone_instructions: "Sii professionale ma amichevole. Fornisci spiegazioni chiare e concise."

# Configurazione delle recensioni
reviews:
  profile: "chill"
  high_level_summary: true
  poem: false
  review_status: true
  commit_status: true
  changed_files_summary: true
  sequence_diagrams: true
  suggested_labels: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
      - "DRAFT"
    drafts: false
  path_filters:
    - "!**/*.md"
    - "!**/*.txt"
    - "!**/bin/**"
    - "!**/obj/**"
    - "!**/.git/**"
    - "!**/.vs/**"
    - "!**/node_modules/**"
chat:
  auto_reply: true
  create_issues: true
knowledge_base:
  issues:
    scope: auto
code_generation:
  docstrings:
    language: en