# Configurazione per il bot Stale
# Numero di giorni di inattività prima che un'issue diventi stale
daysUntilStale: 60
# Numero di giorni di inattività prima che un'issue stale venga chiusa
daysUntilClose: 7
# Issues con queste etichette non diventeranno mai stale
exemptLabels:
  - pinned
  - security
  - bug
  - enhancement
# Etichetta da applicare quando un'issue diventa stale
staleLabel: wontfix
# Commento da postare quando un'issue diventa stale
markComment: >
  Questa issue è stata automaticamente contrassegnata come stale a causa della mancanza di attività recente.
  Verrà chiusa se non ci saranno ulteriori attività nei prossimi 7 giorni. Grazie per il tuo contributo!
# Commento da postare quando un'issue viene chiusa
closeComment: >
  Questa issue è stata automaticamente chiusa a causa della mancanza di attività recente.
  Sentiti libero di riaprirla se ritieni che sia ancora rilevante.