name: Expo CI

on:
  push:
    branches: [ main ]
    paths:
      - 'CollectuApp/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'CollectuApp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CollectuApp
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: './CollectuApp/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test