name: Expo CI

on:
  push:
    branches: [ main , develop]
    paths:
      - 'CollectuApp/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'CollectuApp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CollectuApp
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: './CollectuApp/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup ESLint configuration
      run: |
        # Create ESLint config in the new format for ESLint 9.x
        echo "import globals from 'globals';
        import js from '@eslint/js';
        import tseslint from 'typescript-eslint';

        export default [
          js.configs.recommended,
          ...tseslint.configs.recommended,
          {
            languageOptions: {
              globals: {
                ...globals.browser,
                ...globals.node
              },
            },
            rules: {
              '@typescript-eslint/no-unused-vars': 'warn',
              'import/no-unresolved': 'warn',
              'react-hooks/exhaustive-deps': 'warn'
            }
          }
        ];" > eslint.config.js
    
    - name: Install ESLint dependencies
      run: npm install --save-dev eslint@8.57.0 @eslint/js globals typescript-eslint
    
    - name: Run linter (warnings allowed)
      run: npx eslint@8.57.0 . --max-warnings=100
      
    - name: Run tests
      run: npm test
      
    - name: Build Expo app
      run: npx expo export --platform web