name: Expo CI

on:
  push:
    branches: [ main , develop]
    paths:
      - 'CollectuApp/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'CollectuApp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CollectuApp
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: './CollectuApp/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install specific ESLint version
      run: npm install --save-dev eslint@8.57.0 eslint-config-expo
    
    - name: Setup ESLint configuration
      run: |
        # Create ESLint config using CommonJS syntax for ESLint 8.x
        echo "module.exports = {
          extends: ['eslint-config-expo'],
          rules: {
            '@typescript-eslint/no-unused-vars': 'warn',
            'import/no-unresolved': 'warn',
            'react-hooks/exhaustive-deps': 'warn'
          }
        };" > .eslintrc.js
    
    - name: Run linter (warnings allowed)
      run: npx eslint@8.57.0 . --max-warnings=100
      
    - name: Run tests
      run: npm test
      
    - name: Build Expo app
      run: npx expo export --platform web