name: Release Drafter

on:
  push:
    branches:
      - main
      - develop
  # Permette di eseguire manualmente il workflow dalla tab Actions
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}